/**
 * Generate OperationConfig.json AND OpModules by directly instantiating operations
 * without going through Recipe.mjs (which has the circular dep).
 */
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const opsDir = path.resolve(__dirname, '../../CyberChef/src/core/operations');
const configDir = path.resolve(__dirname, '../../CyberChef/src/core/config');
const modulesDir = path.resolve(configDir, 'modules');

// Operations that depend on Node.js-only APIs and cannot work in a browser.
// - AvroToJSON: uses `avsc` which requires Node.js `SlowBuffer`
// - JWTDecode: uses `jsonwebtoken` which requires Node.js crypto + `SlowBuffer`
const NODE_ONLY_OPS = new Set([
  'AvroToJSON.mjs',   // avsc uses Node.js SlowBuffer
  'JWTDecode.mjs',    // jsonwebtoken uses Node.js crypto + SlowBuffer
  'JWTSign.mjs',      // jsonwebtoken uses Node.js crypto + SlowBuffer
  'JWTVerify.mjs',    // jsonwebtoken uses Node.js crypto + SlowBuffer
]);

// Read all .mjs operation files
const files = fs.readdirSync(opsDir).filter(f => f.endsWith('.mjs') && f !== 'index.mjs');

const operationConfig = {};
// modules: { "Default": { "To Base64": "ToBase64", ... }, ... }
const modules = {};
let loaded = 0;
let failed = 0;

for (const file of files) {
  if (NODE_ONLY_OPS.has(file)) {
    failed++;
    console.warn(`  SKIP ${file}: Node.js-only dependency`);
    continue;
  }
  try {
    const mod = await import(path.join(opsDir, file));
    const OpClass = mod.default;
    const op = new OpClass();
    const className = file.replace('.mjs', '');

    const entry = {
      module: op.module,
      description: op.description,
      infoURL: op.infoURL,
      inputType: op.inputType,
      outputType: op.presentType,
      flowControl: op.flowControl,
      manualBake: op.manualBake,
      args: op.args,
      className,
    };

    // Include checks if defined (needed by Magic for pattern matching)
    if (op.checks && op.checks.length > 0) {
      entry.checks = op.checks;
    }

    operationConfig[op.name] = entry;

    if (!(op.module in modules)) modules[op.module] = {};
    modules[op.module][op.name] = className;

    loaded++;
  } catch (err) {
    failed++;
    console.warn(`  SKIP ${file}: ${err.message.split('\n')[0]}`);
  }
}

// Write OperationConfig.json
fs.writeFileSync(
  path.join(configDir, 'OperationConfig.json'),
  JSON.stringify(operationConfig, null, 4),
);
console.log(`Generated OperationConfig.json: ${loaded} operations loaded, ${failed} skipped`);

// Write module files
if (!fs.existsSync(modulesDir)) fs.mkdirSync(modulesDir, { recursive: true });

for (const module in modules) {
  let code = `/**\n* THIS FILE IS AUTOMATICALLY GENERATED\n*/\n`;

  for (const opName in modules[module]) {
    const objName = modules[module][opName];
    code += `import ${objName} from "../../operations/${objName}.mjs";\n`;
  }

  code += `\nconst OpModules = typeof self === "undefined" ? {} : self.OpModules || {};\n\n`;
  code += `OpModules.${module} = {\n`;
  for (const opName in modules[module]) {
    const objName = modules[module][opName];
    code += `    "${opName}": ${objName},\n`;
  }
  code += `};\n\nexport default OpModules;\n`;

  fs.writeFileSync(path.join(modulesDir, `${module}.mjs`), code);
  console.log(`Written ${module} module`);
}

// Write OpModules.mjs wrapper
let opModulesCode = `/**\n* THIS FILE IS AUTOMATICALLY GENERATED\n*/\n`;

for (const module in modules) {
  opModulesCode += `import ${module}Module from "./${module}.mjs";\n`;
}

opModulesCode += `\nconst OpModules = {};\n\nObject.assign(\n    OpModules,\n`;
for (const module in modules) {
  opModulesCode += `    ${module}Module,\n`;
}
opModulesCode += `);\n\nexport default OpModules;\n`;

fs.writeFileSync(path.join(modulesDir, 'OpModules.mjs'), opModulesCode);
console.log('Written OpModules.mjs');
